In [4]:
import numpy as np
import sys
import os
sys.path.append(os.path.abspath('..'))
from game.tictactoe import TicTacToe

In [5]:
tictactoe = TicTacToe()
player = 1

state = tictactoe.get_initial_state()

while True:
    print(state)
    valid_moves = tictactoe.get_valid_moves(state)
    print("valid_moves", [i for i in range(tictactoe.action_size) if valid_moves[i] == 1])
    action = int(input(f"{player}:"))
    
    if valid_moves[action] == 0:
        print("action not valid")
        continue
        
    state = tictactoe.get_next_state(state, action, player)
    
    value, is_terminal = tictactoe.get_value_and_terminated(state, action)
    
    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break
        
    player = tictactoe.get_opponent(player)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid_moves [0, 1, 2, 3, 4, 5, 6, 7, 8]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid_moves [0, 2, 3, 4, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 3, 4, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 4, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 5, 6, 7, 8]
action not valid
[[ 0.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 5, 6, 7, 8]
action not valid
[[ 0.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 5, 6, 7, 8]
action not valid
[[ 0.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 5, 6, 7, 8]
action not valid
[[ 0.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 5, 6, 7, 8]
action not valid
[[ 0.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 5, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1. -1.  1.]
 [ 0.  0.  0.]]
valid_moves [0, 6, 7, 8]
[[ 0.  1. -1.]
 [ 1. -1.  1.]
 [-1.  0.  0.]]
-1 won
